name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: deploy
      env:
        DEPLOY_TOKEN: ${{secrets.DEPLOY_TOKEN}}
      run: |
        curl -X POST -H 'Content-Type: application/json' 'https://deploy.abelab.dev' -d '{"app": "kc3hack2021", "token": "'"$DEPLOY_TOKEN"'"}'
